# -*- coding: utf-8 -*-
"""crypto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hWIUjKruZKJhpLMNDBGbjmKvoUtV3R8S
"""

!pip install snowflake-connector-python
import requests,json
import pandas as pd
from snowflake.connector.pandas_tools import write_pandas

url="http://api.coincap.io/v2/assets"

from requests.api import head
headers={
    'Accept':'aplication/json',
    'Content-Type': 'aplication/json'
    
}

response=requests.request("GET",url,headers=headers,data={})

my_json=response.json()
print(my_json)

ourdata=[]
for x in my_json['data']:
  listing=[x['symbol'],x['name'],x['priceUsd']]
  ourdata.append(listing)
print(ourdata)

df=pd.DataFrame(ourdata,columns=["symbol","name","priceUsd"])

df

df.to_csv("crypto.csv", index=False)

people = {'data': [{'name': 'John', 'age': '27', 'sex': 'Male'},{'name': 'Marie', 'age': '22', 'sex': 'Female'}],'t':{'2334235'}}

people['data']
for ele in people['data']:
  print(ele['age'])



import getpass
pwd=getpass.getpass("Enter password:")

import snowflake.connector
conn=snowflake.connector.connect(user='admin',
                                 password=str(pwd),
                                 account='nd74893.us-east-2.aws',
                                 warehouse='DWH_01',
                                 database='CRYPTO',
                                 schema='PUBLIC')

#create cursor
curs=conn.cursor()
curs.execute('USE ROLE ACCOUNTADMIN')
curs.execute('USE DATABASE CRYPTO')
curs.execute('USE SCHEMA PUBLIC')
sql='DROP TABLE IF EXISTS  "PUBLIC"."CRYPTOTBL"'
curs.execute(sql)
curs.execute('CREATE TABLE "CRYPTOTBL" ("symbol" STRING ,"name" STRING,"priceUsd" INTEGER)')
df1=pd.read_csv("crypto.csv")
write_pandas(conn,df1,table_name="CRYPTOTBL")

#df=curs.fetch_pandas_all()

df

df1=pd.read_csv("crypto.csv")
df1.head()

!pip freeze >requirements.txt

!pip --version

